organizer/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

app_name = "account"
urlpatterns = [
    #  Login/Logout
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # Password change flow
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # Password reset flow (email)
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("account:password_reset_done")
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("account:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # Register
    path("register/", views.register, name="register"),
    # Edit
    path("edit/", views.edit, name="edit"),
    path('delete/', views.delete, name='delete')
]

organizer/dashboard/api/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register("resources", views.ResourceViewSet, basename='resource')
router.register("tasks", views.TaskViewSet, basename='task')
router.register("notes", views.NotesViewSet, basename='note')
router.register("goals", views.GoalsViewSet, basename='goal')
router.register("posts", views.PostsViewSet, basename='post')
router.register("comments", views.CommentsViewSet, basename='comments')

app_name = "dashboard"
urlpatterns = [
    path("", include(router.urls)),
]

organizer/dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "dashboard"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('resources/', views.resources_list, name='resource_list'),
    path("resource/<int:rid>/", views.resource_detail, name="resource_details"),
    path("notes/list/", views.note_list, name='note_list'),
    path("notes/new/", views.new_note, name='new_note'),
    path("notes/<int:note_id>/", views.note_detail, name="note_detail"),
    path("discussion/", views.discussions, name='discussion_list'),
    path('discussion/new/', views.add_discussion, name='new_discussion'),
    path('discussion/<int:post_id>/newComment/', views.add_comment, name='add_comment'),
    path('discussion/<int:comment_id>/reply/', views.add_reply, name='add_reply'),
    path('discussion/<int:post_id>/', views.post_detail, name='discussion_detail'),
    path('learningLog/new/', views.add_learning_log, name='add_log'),
    path('feedback/', views.add_feedback, name='feedback'),
    path('changelog/', views.changelog, name='changelog'),

    # stripe
    # path('config/', views.stripe_config),
    # path('create-checkout-session/', views.create_checkout_session),
    # path('success/', views.SuccessView.as_view()),
    # path('cancelled/', views.CancelledView.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizer/organizer/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls", namespace="account")),
    path("", include("dashboard.urls", namespace="dashboard")),
    path("api/", include("dashboard.api.urls", namespace="api")),
    path('actions/', include('actions.urls', namespace='actions')),
    path("ping/", views.ping, name="ping"),
]

organizer/dashboard/forms.py
from django import forms

from .models import Resource, Post, Comment, CommentReply, LearningLog, Feedback

class AddFeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('feedback',)

class AddResourceForm(forms.ModelForm):

    url = forms.URLField(required=False)

    class Meta:
        model = Resource
        fields = ("title", "subject", "resource_type", "url", "description")


class AddDiscussionForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ("title", "content")


class AddCommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content',)


class AddCommentReplyForm(forms.ModelForm):

    class Meta:
        model = CommentReply
        fields = ('content',)


class AddLearningLogForm(forms.ModelForm):
    class Meta:
        model = LearningLog
        fields = ('text',)

organizer/dashboard/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import viewsets, status
from rest_framework.authentication import BasicAuthentication, SessionAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from django.contrib import messages

from ..models import Resource, Note, Task, Goal, Post, Comment, Subject
from .serializers import ResourceSerializer, \
    TaskSerializer, NoteSerializer, GoalSerializer, \
    PostSerializer, CommentSerializer
from actions.utils import create_action

class BaseViewSet(viewsets.ModelViewSet):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]


class ResourceViewSet(BaseViewSet):
    queryset = Resource.objects.all()
    serializer_class = ResourceSerializer

    def get_queryset(self):
        user = self.request.user
        return Resource.objects.filter(user=user)

    def create(self, request, *args, **kwargs):
        tasks = request.data["tasks"]
        serializer = ResourceSerializer(data=request.data)
        if serializer.is_valid():
            resource = serializer.save(user=request.user)


            # Add valid tasks
            for task in tasks:
                task["resource"] = resource.id
                task_obj = TaskSerializer(data=task)
                if task_obj.is_valid():
                    task_obj.save()

            # Add subject
            try:
                subject = Subject.objects.get(name=resource.subject)
            except Subject.DoesNotExist:
                subject = Subject.objects.create(name=resource.subject)
            subject.users.add(request.user)
            subject.save()

            messages.success(request, f'"{resource.title}" added to your collection.')

            return Response(
                status=201, data={"msg": "created", "data": serializer.data}
            )
        error_msg = ""
        for field in serializer.errors:
            error_msg += f'{serializer.errors[field][0]}\n'
        messages.error(request, f'Error occurred: ' + error_msg)
        return Response(status=400, data={"msg": serializer.error_messages})

    def destroy(self, request, *args, **kwargs):
        response = super(ResourceViewSet, self).destroy(request, *args, **kwargs)
        messages.success(request, 'Resource Deleted.')
        return response


class TaskViewSet(BaseViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

    def get_queryset(self):
        user = self.request.user
        return Task.objects.filter(resource__user=user)

    def partial_update(self, request, pk=None):
        response = super(TaskViewSet, self).partial_update(request, pk)
        if response.status_code == 200:
            task = get_object_or_404(Task, id=request.data['id'])
            if request.data['status'] and request.data['status'] == 'completed':
                create_action(request.user, 'completed a task', target=task)
        return response


class NotesViewSet(BaseViewSet):
    queryset = Note.objects.all()
    serializer_class = NoteSerializer

    def get_queryset(self):
        user = self.request.user
        return Note.objects.filter(resource__user=user)


class GoalsViewSet(BaseViewSet):
    queryset = Goal.objects.all()
    serializer_class = GoalSerializer

    def get_queryset(self):
        user = self.request.user
        return Goal.objects.filter(user=user)


class PostsViewSet(BaseViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def get_queryset(self):
        user = self.request.user
        return Post.objects.filter(user=user)

    def destroy(self, request, *args, **kwargs):
        response = super(PostsViewSet, self).destroy(request, *args, **kwargs)
        messages.success(request, 'Post Deleted.')
        return response


class CommentsViewSet(BaseViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def get_queryset(self):
        user = self.request.user
        return Comment.objects.filter(user=user)

    def destroy(self, request, *args, **kwargs):
        response = super(CommentsViewSet, self).destroy(request, *args, **kwargs)
        messages.success(request, 'Comment Deleted.')
        return response

organizer/dashboard/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from .forms import AddResourceForm, AddDiscussionForm, AddCommentForm, AddCommentReplyForm, AddLearningLogForm, AddFeedbackForm
from .models import Note, Resource, Task, Subject, Post, Comment, LearningLog
from actions.models import Action
from actions.utils import create_action


@login_required
def dashboard(request):
    profile = request.user.profile
    if profile.first_login:
        profile.first_login = False
        profile.save()
        create_action(request.user, 'joined SkillHQ')
        return redirect(reverse_lazy('account:edit'))


    if request.user.profile.private:
        actions = Action.objects.filter(user=request.user)
    else:
        actions = Action.public.all()
    actions = actions[:300]

    resources = Resource.objects.filter(user=request.user)
    tasks = Task.objects.filter(resource__user=request.user)
    subjects = Subject.objects.all()
    recent_posts = Post.objects.all()[:5]
    return render(
        request,
        "dashboard/dashboard.html",
        {
            "section": "dashboard",
            "resources": resources,
            "tasks": tasks,
            "form": AddResourceForm(),
            "all_subjects": subjects,
            'actions': actions,
            'recent_posts': recent_posts,
        },
    )


@login_required
def resource_detail(request, rid):
    resource = get_object_or_404(Resource, pk=rid)
    if request.user.id != resource.user.id:
        redirect("/")
    return render(
        request,
        "dashboard/resource/detail.html",
        {"section": "detail", "resource": resource, "form": AddResourceForm()},
    )


@login_required
def new_note(request):
    return render(request, 'dashboard/resource/note.html',
                  {'section': 'note',
                   'note': None})


@login_required
def note_detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    if request.user.id != note.resource.user.id:
        redirect("/")
    return render(
        request, "dashboard/resource/note.html", {"section": "note",
                                                  "note": note}
    )


@login_required
def note_list(request):
    notes = Note.objects.filter(resource__user=request.user)
    subjects = request.user.subjects.all()

    subject_filter = request.GET.get('subject')
    subject = None
    if subject_filter:
        subject = Subject.objects.get(name=subject_filter)
        notes = notes.filter(resource__subject=subject.name)

    return render(request, 'dashboard/dashboard_notes.html', {
        'section': 'notes',
        'notes': notes,
        'subjects': subjects,
        'selected_subject': subject.name if subject else None,
    })


@login_required
def resources_list(request):
    tasks = Task.objects.filter(resource__user=request.user)
    resources = Resource.objects.filter(user=request.user)

    subject_filter = request.GET.get('subject')
    subject = None
    if subject_filter:
        subject = Subject.objects.get(name=subject_filter)
        resources = resources.filter(subject=subject.name)

    resources_paused = resources.filter(status='Not Started/On Hold')
    resources_in_progress = resources.filter(status='In Progress')
    resources_completed = resources.filter(status="Completed")



    subjects = request.user.subjects.all()
    return render(
        request,
        "dashboard/dashboard_resources.html",
        {
            "section": "resources",
            "resources_paused": resources_paused,
            "resources_in_progress": resources_in_progress,
            "resources_completed": resources_completed,
            "tasks": tasks,
            "form": AddResourceForm(),
            'subjects': subjects,
            'selected_subject': subject.name if subject else None,
            "all_subjects": Subject.objects.all()
        },
    )


@login_required
def discussions(request):
    posts = Post.objects.all()
    return render(request, 'dashboard/dashboard_discussion.html', {
        'section': 'discussion',
        'posts': posts,
    })


@login_required
def add_discussion(request):
    error = None
    if request.method == "POST":
        form = AddDiscussionForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, f'"{post.title}" added.')
            create_action(request.user, 'started discussion', post)
            return redirect(reverse_lazy('dashboard:discussion_list'))
        else:
            error = "Error adding post"
    return render(request, 'dashboard/posts/new.html', {
        'form': AddDiscussionForm(),
        'error': error
    })


@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'dashboard/posts/detail.html', {
        'post': post
    })


@login_required
@require_POST
def add_comment(request, post_id):
    form = AddCommentForm(data=request.POST)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post = post
        form.save()
        messages.success(request, 'comment added.')
    else:
        messages.error(request, "Can't add comment.")
    return redirect(reverse_lazy("dashboard:discussion_detail", args=(post.id,)))


@login_required
@require_POST
def add_reply(request, comment_id):
    form = AddCommentReplyForm(data=request.POST)
    comment = get_object_or_404(Comment, pk=comment_id)
    if form.is_valid():
        reply = form.save(commit=False)
        reply.user = request.user
        reply.comment = comment
        form.save()
        messages.success(request, 'comment added.')
    else:
        messages.error(request, "Can't add comment.")
    return redirect(reverse_lazy("dashboard:discussion_detail", args=(comment.post.id,)))


@login_required
@require_POST
def add_learning_log(request):
    form = AddLearningLogForm(data=request.POST)
    if form.is_valid():
        log = form.save(commit=False)
        log.user = request.user
        log.save()
        messages.success(request, 'Learning achievement logged')
        create_action(request.user, 'learned today:', log)
    else:
        messages.error(request, "Can't add to log")
    return redirect(reverse_lazy('dashboard:dashboard'))


@login_required
def profile(request, username):
    user = get_object_or_404(User, username=username)
    if user.profile.private and request.user != user:
        return redirect(reverse_lazy('dashboard:dashboard'))
    return render(request, 'dashboard/profile/profile.html', {
        'user': user
    })



@login_required
@require_POST
def add_feedback(request):
    form = AddFeedbackForm(data=request.POST)
    if form.is_valid():
        feedback = form.save(commit=False)
        feedback.user = request.user
        feedback.save()
        messages.success(request, 'Feedback submitted! Thank you!')
    else:
        messages.error(request, 'Error while submitting feedback.')
    return redirect(reverse_lazy('dashboard:dashboard'))


def changelog(request):
    return render(request, 'info/changelog.html')

organizer/dashboard/templates/dashboard/dashboard.html
{% extends "app_base.html" %}

{% load static %}

{% block title %}
Dashboard
{% endblock %}

{% block js %}
  <script src="{% static 'js/dashboard.js' %}"></script>
{% endblock %}

{% block sidebar %}
<div class="mt-4 bg-white sm:rounded-md px-4 py-5 text-gray-900 leading-8">
<p>Recent Discussions</p>
    <ul>
        {% for post in recent_posts %}
        <li class="text-xs">
            <a class="text-indigo-600 hover:text-indigo-400" href="{% url 'dashboard:discussion_detail' post.id %}">{{ post.title }}</a>
            <div class="-mt-4">
                <small>{{ post.comments.count }} Comments</small>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

<!--<div class="mt-4">-->
<!--    <a class="bg-indigo-400 p-2 rounded shadow text-white px-2" href="https://discord.gg/Xn2vdd">Join Our Discord Server</a>-->
<!--</div>-->

{% endblock %}

{% block app_content %}


<main x-data="{ showSlideover: false }">
  <div class="mx-auto sm:px-6 lg:px-8">
  <div class="bg-white overflow-hidden sm:rounded-md mb-4">
      <ul>
        <li>
          <div class="bg-white px-4 py-5 sm:px-6">
                  <div class="-ml-4 -mt-2">
                    <div class="ml-4 mt-2">
                      <h3 class="text-lg leading-6 font-medium text-gray-900">
                        What Did you learn Today?
                      </h3>
                        <p class="text-gray-400 text-sm font-medium">Learning Log - Share new things you learned</p>
                    </div>
                  </div>
              <div class="mt-2">
                  <form id="log-form" action="{% url 'dashboard:add_log' %}" method="POST">
                      {% csrf_token %}
                  <div class="mt-1 relative rounded-md shadow-sm">
                    <input name="text" class="form-input block w-full sm:text-sm sm:leading-5" placeholder="What did you learn today?">
                  </div>
                  <span class="inline-flex rounded-md shadow-sm">
                        <button type="submit" class="mt-2 inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700">
                          Submit
                        </button>
                      </span>
                  </form>
            </div>
        </div>
        </li>
      </ul>
  </div>



  <div class="bg-white overflow-hidden sm:rounded-md mb-4">
      <ul>
        <li>
          <div class="bg-white px-4 py-5 sm:px-6">
                  <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-no-wrap">
                    <div class="ml-4 mt-2">
                      <h3 class="text-lg leading-6 font-medium text-gray-900">
                        Feed
                      </h3>
                    </div>
                    <div class="ml-4 mt-2 flex-shrink-0">
                      <span class="inline-flex rounded-md shadow-sm">
                        <a href="{% url 'dashboard:new_discussion' %}" class="inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700">
                          Add Discussion Post
                        </a>
                      </span>
                    </div>
                  </div>
                </div>
        </li>
        {% for action in actions %}
          {% if action.verb != "joined SkillHQ" %}
          <li>
              <div class="bg-gray-50 px-4 py-5 sm:px-6 m-4 flex items-center justify-between">

                  <div class="flex items-center">
                      {% if action.user.profile.photo %}
                      <img class="mr-2 object-cover object-center border-2 border-indigo-500 inline-block h-10 w-10 rounded-full" src="{% if action.user.profile.photo %}{{ action.user.profile.photo.url }}{% endif %}" alt="{{ action.user.username}}'s profile picture">
                      {% else  %}
                      <span class="mr-2 inline-block h-10 w-10 rounded-full bg-gray-100 border-2 border-indigo-500">
                        <svg class="h-full w-full text-gray-300 rounded-full" fill="currentColor" viewBox="0 0 24 24">
                          <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
                        </svg>
                      </span>
                      {% endif %}
                      <div>
                          <div>
                              <a href="{% url 'dashboard:profile' action.user.username %}" class="text-indigo-500 font-medium">@{{ action.user.username }}</a>
                              <span>{{ action.verb }}
                                  {% if action.target %}
                                    {% if action.verb == 'started discussion' %}<a class="text-indigo-500" href="{% url 'dashboard:discussion_detail' action.target.id %}">{{ action.target }}</a>{% endif %}
                                    {% if action.verb == 'learned today:' %}<span class="text-gray-500">{{ action.target }}</span>{% endif %}
                                    {% if action.verb == 'completed a task' %}<span class="text-gray-500">{{ action.target }}</span>{% endif %}
                                  {% endif %}
                              </span>
                          </div>
                          <p class="text-gray-500 text-sm">{{ action.created|timesince }} ago</p>
                      </div>
                  </div>
                   {% with total_likes=action.users_like.count  %}
                    <div x-data="{ totalLikes: '{{ total_likes }}', actionId: '{{ action.id }}', action: '{% if request.user in action.users_like.all  %}un{% endif %}like'}">
                        <button @click="likeAction(actionId, action);
                        if ( action == 'like' ) {
                         action = 'unlike';
                           totalLikes = String(parseInt(totalLikes)+1)} else {
                          action = 'like';
                           totalLikes = String(parseInt(totalLikes)-1)};"
                                class="group cursor-pointer flex items-center rounded shadow-sm p-1 hover:bg-indigo-100 active:bg-indigo-500">
                            <span x-text="totalLikes" class="group-hover:text-indigo-300 text-gray-500 text-sm"
                            :class="{ 'text-gray-400': action == 'unlike' }"></span>
                            <span class="ml-2">
                                <svg class="h-6 w-6 text-gray-300 group-hover:text-indigo-300" :class="{ 'text-indigo-400': action == 'unlike' }" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M5 2a1 1 0 011 1v1h1a1 1 0 010 2H6v1a1 1 0 01-2 0V6H3a1 1 0 010-2h1V3a1 1 0 011-1zm0 10a1 1 0 011 1v1h1a1 1 0 110 2H6v1a1 1 0 11-2 0v-1H3a1 1 0 110-2h1v-1a1 1 0 011-1zM12 2a1 1 0 01.967.744L14.146 7.2 17.5 9.134a1 1 0 010 1.732l-3.354 1.935-1.18 4.455a1 1 0 01-1.933 0L9.854 12.8 6.5 10.866a1 1 0 010-1.732l3.354-1.935 1.18-4.455A1 1 0 0112 2z" clip-rule="evenodd"></path></svg>
                            </span>
                        </button>
                    </div>
                  {% endwith %}
              </div>

          </li>
        {% endif %}
        {% endfor %}


      </ul>

  </div>
</div>

    </main>
{% endblock %}

organizer/dashboard/templates/dashboard/dashboard_notes.html
{% extends "app_base.html" %}

{% load static %}

{% block title %}
Dashboard
{% endblock %}

{% block js %}
{% endblock %}

{% block sidebar %}
{% url 'dashboard:note_list' as the_url %}
{% include "shared/subject_sort.html" with endpoint=the_url %}
{% endblock %}


{% block app_content %}


<main>
  <div class="mx-auto sm:px-6 lg:px-8">
    <!-- Materials Card -->
    <div class="bg-white overflow-hidden sm:rounded-md">
      <ul>
        <li>
          <div class="bg-white px-4 py-5 sm:px-6">
                  <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-no-wrap">
                    <div class="ml-4 mt-2">
                      <h3 class="text-lg leading-6 font-medium text-gray-900">
                        Notes
                      </h3>
                    </div>
                    <div class="hidden ml-4 mt-2 flex-shrink-0">
                      <span class="inline-flex rounded-md shadow-sm">
                        <a href="#" class="inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700">
                          Add New Note
                        </a>
                      </span>
                    </div>
                  </div>
                </div>
        </li>
      </ul>

      <div class="p-4">
        <ul class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {% for note in notes %}
          <li class="col-span-1 bg-white rounded-lg shadow">
            <div class="w-full flex items-center justify-between p-6 space-x-6">
              <div class="flex-1 truncate">
                <div class="flex items-center space-x-3">
                  <h3 class="text-gray-900 text-sm leading-5 font-medium truncate">{{ note.title }}</h3>
                  <span class="flex-shrink-0 inline-block px-2 py-0.5 text-teal-800 text-xs leading-4 font-medium bg-teal-100 rounded-full">{{ note.resource.subject }}</span>
                </div>
                <p class="mt-1 text-gray-500 text-sm leading-5 truncate">{{ note.resource.title }}</p>
              </div>
<!--              <img class="w-10 h-10 bg-gray-300 rounded-full flex-shrink-0" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=60" alt="">-->
            </div>
            <div class="border-t border-gray-200">
              <div class="-mt-px flex">
                <div class="w-0 flex-1 flex border-r border-gray-200">
                  <a href="{% url 'dashboard:note_detail' note.id %}" class="group hover:bg-indigo-300 hover:text-indigo-700 relative -mr-px w-0 flex-1 inline-flex items-center justify-center py-4 text-sm leading-5 text-gray-700 font-medium border border-transparent rounded-bl-lg hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 transition ease-in-out duration-150">

                    <svg class="w-5 h-5 text-gray-400 group-hover:text-indigo-700"
                            fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path><path d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg>
                    <span class="ml-3">View</span>
                  </a>
                </div>
<!--                <div class="-ml-px w-0 flex-1 flex">-->
<!--                  <a href="#" class="group hover:bg-red-300 hover:text-red-700 relative w-0 flex-1 inline-flex items-center justify-center py-4 text-sm leading-5 text-gray-700 font-medium border border-transparent rounded-br-lg hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 transition ease-in-out duration-150">-->
<!--                    <svg class="w-5 h-5 text-gray-400 group-hover:text-red-700"   fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>-->
<!--                    <span class="ml-3">Delete</span>-->
<!--                  </a>-->
<!--                </div>-->
              </div>
            </div>
          </li>
          {% endfor %}
</ul>

      </div>

  </div>
</div>

    </main>
{% endblock %}