organizer/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

app_name = "account"
urlpatterns = [
    #  Login/Logout
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # Password change flow
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # Password reset flow (email)
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("account:password_reset_done")
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("account:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # Register
    path("register/", views.register, name="register"),
    # Edit
    path("edit/", views.edit, name="edit"),
    path('delete/', views.delete, name='delete')
]

organizer/dashboard/api/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register("resources", views.ResourceViewSet, basename='resource')
router.register("tasks", views.TaskViewSet, basename='task')
router.register("notes", views.NotesViewSet, basename='note')
router.register("goals", views.GoalsViewSet, basename='goal')
router.register("posts", views.PostsViewSet, basename='post')
router.register("comments", views.CommentsViewSet, basename='comments')

app_name = "dashboard"
urlpatterns = [
    path("", include(router.urls)),
]

organizer/dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "dashboard"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('resources/', views.resources_list, name='resource_list'),
    path("resource/<int:rid>/", views.resource_detail, name="resource_details"),
    path("notes/list/", views.note_list, name='note_list'),
    path("notes/new/", views.new_note, name='new_note'),
    path("notes/<int:note_id>/", views.note_detail, name="note_detail"),
    path("discussion/", views.discussions, name='discussion_list'),
    path('discussion/new/', views.add_discussion, name='new_discussion'),
    path('discussion/<int:post_id>/newComment/', views.add_comment, name='add_comment'),
    path('discussion/<int:comment_id>/reply/', views.add_reply, name='add_reply'),
    path('discussion/<int:post_id>/', views.post_detail, name='discussion_detail'),
    path('learningLog/new/', views.add_learning_log, name='add_log'),
    path('feedback/', views.add_feedback, name='feedback'),
    path('changelog/', views.changelog, name='changelog'),

    # stripe
    # path('config/', views.stripe_config),
    # path('create-checkout-session/', views.create_checkout_session),
    # path('success/', views.SuccessView.as_view()),
    # path('cancelled/', views.CancelledView.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizer/organizer/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls", namespace="account")),
    path("", include("dashboard.urls", namespace="dashboard")),
    path("api/", include("dashboard.api.urls", namespace="api")),
    path('actions/', include('actions.urls', namespace='actions')),
    path("ping/", views.ping, name="ping"),
]

organizer/dashboard/forms.py
from django import forms

from .models import Resource, Post, Comment, CommentReply, LearningLog, Feedback

class AddFeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('feedback',)

class AddResourceForm(forms.ModelForm):

    url = forms.URLField(required=False)

    class Meta:
        model = Resource
        fields = ("title", "subject", "resource_type", "url", "description")


class AddDiscussionForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ("title", "content")


class AddCommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content',)


class AddCommentReplyForm(forms.ModelForm):

    class Meta:
        model = CommentReply
        fields = ('content',)


class AddLearningLogForm(forms.ModelForm):
    class Meta:
        model = LearningLog
        fields = ('text',)

organizer/dashboard/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import viewsets, status
from rest_framework.authentication import BasicAuthentication, SessionAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from django.contrib import messages

from ..models import Resource, Note, Task, Goal, Post, Comment, Subject
from .serializers import ResourceSerializer, \
    TaskSerializer, NoteSerializer, GoalSerializer, \
    PostSerializer, CommentSerializer
from actions.utils import create_action

class BaseViewSet(viewsets.ModelViewSet):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]


class ResourceViewSet(BaseViewSet):
    queryset = Resource.objects.all()
    serializer_class = ResourceSerializer

    def get_queryset(self):
        user = self.request.user
        return Resource.objects.filter(user=user)

    def create(self, request, *args, **kwargs):
        tasks = request.data["tasks"]
        serializer = ResourceSerializer(data=request.data)
        if serializer.is_valid():
            resource = serializer.save(user=request.user)


            # Add valid tasks
            for task in tasks:
                task["resource"] = resource.id
                task_obj = TaskSerializer(data=task)
                if task_obj.is_valid():
                    task_obj.save()

            # Add subject
            try:
                subject = Subject.objects.get(name=resource.subject)
            except Subject.DoesNotExist:
                subject = Subject.objects.create(name=resource.subject)
            subject.users.add(request.user)
            subject.save()

            messages.success(request, f'"{resource.title}" added to your collection.')

            return Response(
                status=201, data={"msg": "created", "data": serializer.data}
            )
        error_msg = ""
        for field in serializer.errors:
            error_msg += f'{serializer.errors[field][0]}\n'
        messages.error(request, f'Error occurred: ' + error_msg)
        return Response(status=400, data={"msg": serializer.error_messages})

    def destroy(self, request, *args, **kwargs):
        response = super(ResourceViewSet, self).destroy(request, *args, **kwargs)
        messages.success(request, 'Resource Deleted.')
        return response


class TaskViewSet(BaseViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

    def get_queryset(self):
        user = self.request.user
        return Task.objects.filter(resource__user=user)

    def partial_update(self, request, pk=None):
        response = super(TaskViewSet, self).partial_update(request, pk)
        if response.status_code == 200:
            task = get_object_or_404(Task, id=request.data['id'])
            if request.data['status'] and request.data['status'] == 'completed':
                create_action(request.user, 'completed a task', target=task)
        return response


class NotesViewSet(BaseViewSet):
    queryset = Note.objects.all()
    serializer_class = NoteSerializer

    def get_queryset(self):
        user = self.request.user
        return Note.objects.filter(resource__user=user)


class GoalsViewSet(BaseViewSet):
    queryset = Goal.objects.all()
    serializer_class = GoalSerializer

    def get_queryset(self):
        user = self.request.user
        return Goal.objects.filter(user=user)


class PostsViewSet(BaseViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def get_queryset(self):
        user = self.request.user
        return Post.objects.filter(user=user)

    def destroy(self, request, *args, **kwargs):
        response = super(PostsViewSet, self).destroy(request, *args, **kwargs)
        messages.success(request, 'Post Deleted.')
        return response


class CommentsViewSet(BaseViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def get_queryset(self):
        user = self.request.user
        return Comment.objects.filter(user=user)

    def destroy(self, request, *args, **kwargs):
        response = super(CommentsViewSet, self).destroy(request, *args, **kwargs)
        messages.success(request, 'Comment Deleted.')
        return response

organizer/dashboard/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from .forms import AddResourceForm, AddDiscussionForm, AddCommentForm, AddCommentReplyForm, AddLearningLogForm, AddFeedbackForm
from .models import Note, Resource, Task, Subject, Post, Comment, LearningLog
from actions.models import Action
from actions.utils import create_action


@login_required
def dashboard(request):
    profile = request.user.profile
    if profile.first_login:
        profile.first_login = False
        profile.save()
        create_action(request.user, 'joined SkillHQ')
        return redirect(reverse_lazy('account:edit'))


    if request.user.profile.private:
        actions = Action.objects.filter(user=request.user)
    else:
        actions = Action.public.all()
    actions = actions[:300]

    resources = Resource.objects.filter(user=request.user)
    tasks = Task.objects.filter(resource__user=request.user)
    subjects = Subject.objects.all()
    recent_posts = Post.objects.all()[:5]
    return render(
        request,
        "dashboard/dashboard.html",
        {
            "section": "dashboard",
            "resources": resources,
            "tasks": tasks,
            "form": AddResourceForm(),
            "all_subjects": subjects,
            'actions': actions,
            'recent_posts': recent_posts,
        },
    )


@login_required
def resource_detail(request, rid):
    resource = get_object_or_404(Resource, pk=rid)
    if request.user.id != resource.user.id:
        redirect("/")
    return render(
        request,
        "dashboard/resource/detail.html",
        {"section": "detail", "resource": resource, "form": AddResourceForm()},
    )


@login_required
def new_note(request):
    return render(request, 'dashboard/resource/note.html',
                  {'section': 'note',
                   'note': None})


@login_required
def note_detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    if request.user.id != note.resource.user.id:
        redirect("/")
    return render(
        request, "dashboard/resource/note.html", {"section": "note",
                                                  "note": note}
    )


@login_required
def note_list(request):
    notes = Note.objects.filter(resource__user=request.user)
    subjects = request.user.subjects.all()

    subject_filter = request.GET.get('subject')
    subject = None
    if subject_filter:
        subject = Subject.objects.get(name=subject_filter)
        notes = notes.filter(resource__subject=subject.name)

    return render(request, 'dashboard/dashboard_notes.html', {
        'section': 'notes',
        'notes': notes,
        'subjects': subjects,
        'selected_subject': subject.name if subject else None,
    })


@login_required
def resources_list(request):
    tasks = Task.objects.filter(resource__user=request.user)
    resources = Resource.objects.filter(user=request.user)

    subject_filter = request.GET.get('subject')
    subject = None
    if subject_filter:
        subject = Subject.objects.get(name=subject_filter)
        resources = resources.filter(subject=subject.name)

    resources_paused = resources.filter(status='Not Started/On Hold')
    resources_in_progress = resources.filter(status='In Progress')
    resources_completed = resources.filter(status="Completed")



    subjects = request.user.subjects.all()
    return render(
        request,
        "dashboard/dashboard_resources.html",
        {
            "section": "resources",
            "resources_paused": resources_paused,
            "resources_in_progress": resources_in_progress,
            "resources_completed": resources_completed,
            "tasks": tasks,
            "form": AddResourceForm(),
            'subjects': subjects,
            'selected_subject': subject.name if subject else None,
            "all_subjects": Subject.objects.all()
        },
    )


@login_required
def discussions(request):
    posts = Post.objects.all()
    return render(request, 'dashboard/dashboard_discussion.html', {
        'section': 'discussion',
        'posts': posts,
    })


@login_required
def add_discussion(request):
    error = None
    if request.method == "POST":
        form = AddDiscussionForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, f'"{post.title}" added.')
            create_action(request.user, 'started discussion', post)
            return redirect(reverse_lazy('dashboard:discussion_list'))
        else:
            error = "Error adding post"
    return render(request, 'dashboard/posts/new.html', {
        'form': AddDiscussionForm(),
        'error': error
    })


@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'dashboard/posts/detail.html', {
        'post': post
    })


@login_required
@require_POST
def add_comment(request, post_id):
    form = AddCommentForm(data=request.POST)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post = post
        form.save()
        messages.success(request, 'comment added.')
    else:
        messages.error(request, "Can't add comment.")
    return redirect(reverse_lazy("dashboard:discussion_detail", args=(post.id,)))


@login_required
@require_POST
def add_reply(request, comment_id):
    form = AddCommentReplyForm(data=request.POST)
    comment = get_object_or_404(Comment, pk=comment_id)
    if form.is_valid():
        reply = form.save(commit=False)
        reply.user = request.user
        reply.comment = comment
        form.save()
        messages.success(request, 'comment added.')
    else:
        messages.error(request, "Can't add comment.")
    return redirect(reverse_lazy("dashboard:discussion_detail", args=(comment.post.id,)))


@login_required
@require_POST
def add_learning_log(request):
    form = AddLearningLogForm(data=request.POST)
    if form.is_valid():
        log = form.save(commit=False)
        log.user = request.user
        log.save()
        messages.success(request, 'Learning achievement logged')
        create_action(request.user, 'learned today:', log)
    else:
        messages.error(request, "Can't add to log")
    return redirect(reverse_lazy('dashboard:dashboard'))


@login_required
def profile(request, username):
    user = get_object_or_404(User, username=username)
    if user.profile.private and request.user != user:
        return redirect(reverse_lazy('dashboard:dashboard'))
    return render(request, 'dashboard/profile/profile.html', {
        'user': user
    })



@login_required
@require_POST
def add_feedback(request):
    form = AddFeedbackForm(data=request.POST)
    if form.is_valid():
        feedback = form.save(commit=False)
        feedback.user = request.user
        feedback.save()
        messages.success(request, 'Feedback submitted! Thank you!')
    else:
        messages.error(request, 'Error while submitting feedback.')
    return redirect(reverse_lazy('dashboard:dashboard'))


def changelog(request):
    return render(request, 'info/changelog.html')

organizer/dashboard/templates/dashboard/resource/note.html
{% extends "app_base.html" %}

{% block title %}
{{ resource.title }}
{% endblock %}

{% load dashboard_tags %}

{% load static %}

{% block js %}
  <script src="{% static 'js/notes.js' %}"></script>
{% endblock %}

{% block app_content %}
<form id="details-form" class="hidden">
    {% csrf_token %}
  </form>




<div x-data="{ content: '', 'title': '' }" class="bg-white shadow overflow-hidden sm:rounded-lg max-w-7xl mx-auto sm:px-6 lg:px-8">
  <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
        {{ resource.title|title }}
    </h3>
    <p class="mt-1 max-w-2xl text-sm leading-5 text-gray-500">
        {{ resource.resource_type }}
    </p>
  </div>
  <div class="px-4 py-5 sm:px-6">
      {% if not note %}
      <div>
          <div class="flex ">
              <div class="w-4/5">
                  <label for="title" class="sr-only">Title</label>
                  <div class="relative rounded-md shadow-sm">
                      <input x-model="title" id="title" class="form-input block w-full sm:text-sm sm:leading-5" placeholder="Post Title">
                  </div>
              </div>
              <button @click="addNote(title, content)" class="ml-2 w-1/5 px-2 py-1 bg-indigo-600 text-white rounded">
                  Add Note
              </button>
          </div>

          <div class="border mt-4 w-full">
            <textarea class="p-2 w-full" x-model="content"  name="content" id="" rows="100">
            </textarea>
          </div>
      </div>
      {% else %}
        <div class="prose lg:prose-xl">
            {{ note.content|markdown }}
        </div>
      {% endif %}



  </div>
</div>



{% endblock %}

organizer/dashboard/templates/dashboard/resource/row.html
<li class="border-t border-gray-200">
  <a href="{% url 'dashboard:resource_details' r.id %}" class="block hover:bg-gray-50 focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out">
    <div class="flex items-center px-4 py-4 sm:px-6">
      <div class="min-w-0 flex-1 flex items-center">
        <div class="min-w-0 flex-1 px-4 md:grid md:grid-cols-2 md:gap-4">
          <div>
            <div class="text-sm leading-5 font-medium text-indigo-600 truncate">{{ r.title }}</div>
            <div class="mt-2 flex items-center text-sm leading-5 text-gray-500">

              {% if r.resource_type == "Video Course" %}
              <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path><path d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg>
              {% elif r.resource_type == "Text Course" %}
              <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path><path d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg>
              {% elif r.resource_type == "Text Tutorial" %}
              <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path><path d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg>
              {% elif r.resource_type == "Video Tutorial" %}
              <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path><path d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg>
              {% elif r.resource_type == "eBook" %}
              <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path></svg>
              {% elif r.resource_type == "Book" %}
              <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path></svg>
              {% elif r.resource_type == "Newsletter" %}
              <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path></svg>
              {% elif r.resource_type == "Other" %}
              <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path><path d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg>
              {% endif %}
              <span class="truncate">{{ r.resource_type }}</span>
            </div>
          </div>
          <div class="hidden md:block">
            <div>
              <div class="text-sm leading-5 text-gray-900">
                Added on
                <time datetime="2020-01-07">{{ r.created }}</time>
              </div>
              <div class="mt-2 flex items-center text-sm leading-5 text-gray-500">

                {% if r.status == "Not Started/On Hold" %}
                <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M10 9v6m4-6v6m7-3a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                {% elif r.status == "Completed" %}
                <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-green-400" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                </svg>
                {% elif r.status == "In Progress" %}
                <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-yellow-400"  fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M8 12h.01M12 12h.01M16 12h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                {% endif %}
                {{ r.status }}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div>
        <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
        </svg>
      </div>
    </div>
  </a>
</li>